redux-json-api/redux-json-api

src/jsonapi.js

Adding responses to __onSuccess__ callback, as first parameter on:
1. __readEndpoint__ returns JSON parameter.
1. __createEntity__ returns JSON parameter.
1. __updateEntity__ return JSON parameter.

Added API Response to onSucess

---

src/jsonapi.js
src/utils.js

Issue occurred when content-type header would contains other params, e.g. charset. The check if a valid JSON content-type was responded with, did not pass and the module would not attempt to parse the body as JSON.
Linked issues: #13 #14 #15

[1.3.5] Fix issue with content-type parsing

---

src/utils.js

It's a small detail, but in some cases it makes the whole library unusable.
Some implementations of the `fetch` API send an `Accept: */*` parameter, which doesn't work well with many APIs (such as Flask and Tornado JSON API implementations). 
According to the JSON API specification there shouldn't be any issues caused by sending this header in every request, and it seems to solve the problem.
Maybe it would be useful to be able to edit the default headers for fetch calls in a future release.

Add Accept header (required by some JSON API implementations)

---

src/jsonapi.js

Payload should be passed as `{type: ..., id: ...}` but actually it passed as `{entity: {type: ..., id: ...}}` on `API_UPDATE_FAILED` and `API_DELETE_FAILED`.

Fixed API_{UPDATE|DELETE}_FAILED reducers.

---

.gitignore

I'm the person who's using node version manager, https://github.com/creationix/nvm . I set up `.nvmrc` file for every js project, but I don't think I have to commit it here...

Add .nvmrc to .gitignore

---

src/state-mutation.js
test/jsonapi.js

Currently the updateReverseRelationship function returns the length of the array instead of the relation list on line 36 when there are multiple entities in the response data. This naturally results in an error.
Creating the newRelation as an immutable list should fix it.

fix return value for updateReverseRelationship

---

src/state-mutation.js
test/jsonapi.js
test/payloads/withNonMatchingReverseRelationships.json

In cases where an entity has a relationship of which it's foreign entity does not exist in the state, the last entity of same type will be wrongfully updated to have it's reverse relationship updated.

Relationships with no matching foreign entity may updated other entities incorrectly

---

docs/set-up-configure.md
src/constants.js
src/jsonapi.js
src/utils.js
test/jsonapi.js

I needed to have CSRF tokens submitted as part of a section of a 'mostly' server side HTML rails app. I updated the docs with how it works, and left 'setAccessToken' action intact.

Allow any headers in requests

---

package.json
src/jsonapi.js
src/state-mutation.js
src/utils.js
test/jsonapi.js

Addresses issue #60
- Add `fetch-mock` to dev dependencies for testing
- Update the import for `isomorphic-fetch` to fix issue with [`fetch-mock`] (https://github.com/wheresrhys/fetch-mock#troubleshooting-and-alternative-installation)
- Update state-mutation.js to handle undefined entity.get('relationships') when removing entities from state

Update apiRequest to handle status code 204

---

docs/api.md

The anchor links at the top of docs/api.md have not been working for a few weeks now.
Somehow I keep clicking on them.
Tiny pull request to fix the anchor links to put to the correct anchor tags further down in the document and make things better for all :)

Api Docs - Fix broken anchor links

---

package.json
src/constants.js

Hello!
`keykey` library is only used in one file and it depends on other two libraries:
```
+-- keykey@2.1.1
| `-- lru-cache@3.2.0
|   `-- pseudomap@1.0.2
```
The functionality is very simple, so I think it's a good idea to remove it and reduce the number of dependencies. I tested the changes and they work.

Remove unnecessary keykey dependency

---

src/jsonapi.js

Resolves https://github.com/dixieio/redux-json-api/issues/65
Calls to fetch just need to have credentials: 'include', added to them to once again pass credential information across like jQuery ajax requests do by default.
Reference: https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending-credentials-with-a-fetch-request
> Sending Credentials with a Fetch Request
> 
> Should you want to make a fetch request with credentials such as cookies, you should set the credentials of the request to “include”.
> 
> fetch(url, {  
>   credentials: 'include'  
> })

Enhances fetch requests to include credential cookies

---

.babelrc
.npmignore

I am not entirely sure why this is causing a problem for our react native app but just the presence of the .babelrc file in the npm package causes an error. 
I have re-published this change and confirmed it works. Let me know if you want any more details.

Fix NPM package for react-native

---

package.json
src/jsonapi.js

Hey Folks, me again 👋 
This PR is to allow redux-json-api to work effectively in react-native, which it currently doesn't because of a known issue: https://github.com/matthew-andrews/isomorphic-fetch/issues/59
I don't really know the politics of the decision but it seems like isomorphic-fetch doesn't want to implement the fix that would solve this issue: https://github.com/matthew-andrews/isomorphic-fetch/pull/63 even though github have already implemented a fix themselves in their equivalent repository https://github.com/github/fetch/pull/253
As fetch is a standard there is literally no code change (as you can see by the PR) and everything just works as expected 👍 Let me know if you have any questions.

moving from isomorphic-fetch to fetch-everywhere

---

CONTRIBUTING.md

I just submitted a code PR but forgot to run a linter (outside of the one running in my editor). I've added instructions to do this to the contribution guidelines.

adding lint guidelines to contrib

---

src/jsonapi.js
src/state-mutation.js
test/jsonapi.js
test/state-mutation.js

Resolves #98 
- Added a `insertResourcesTypeIntoState` to `state-mutation` file. This function inserts an empty resources collection to the state.
- Calling this function when handling `API_WILL_UPDATE` in the reducer, in order to prepare the state for `setIsInvalidatingForExistingResource` which assumes that the resource type exists as a property on the state.
- Added unit test.

add empty resources type to state before updating if the type doesn't exist

---

src/constants.js
src/jsonapi.js
test/jsonapi.js

Previous conversation here https://github.com/dixieio/redux-json-api/pull/123
Upon application boot, you may want to hydrate the API store with existing information. As an outside user, I should not be dependent on the internal structure of the store for hydration. Instead, I should be able to pass in a JSON-API blob and get the same result that I would if I read the data from an endpoint.
In order to give the user flexibility in how to hydrate the store, as well as preserving server-side rendering compatibility, I have opted not to get hydration data from a global object, instead exposing the synchronous action `hydrateStore`.
It may not make sense to call this `hydrateStore` since you could use this for purposes other than hydration. However, `hydrateStore` seems to fit better with the …

Add ability to hydrate store

---

src/jsonapi.js
test/jsonapi.js

When update or delete fails, isUpdating/isDeleting flags should be decremented but they are incremented.

Fix isUpdating and isDeleting flags when update/delete fails

---

src/utils.js
test/utils.js

From spec: "Keys MUST either be omitted or have a null value to indicate
that a particular link is unavailable."

Fix pagination links when values are null.

---

src/state-mutation.js
test/state-mutation.js

When an endpoint returns data without a relationships attribute, the following code crashes : 
```
const relationships = {};
for (const relationship in resource.relationships) {
if (!resource.relationships[relationship].data) {
relationships[relationship] = resources[idx].relationships[relationship];
}
}
Object.assign(resource.relationships, relationships);
^^^^^^^^^^^
if (!equal(resources[idx], resource)) {
newState = imm.set(newState, updatePath.concat(idx), resource);
}
```
Because `Object` can't assign to `undefined`.
The [json api](http://jsonapi.org/format/#document-resource-objects) spec does say that the `relationships` MAY be present, but necessarly : 
```
In addition, a resource object MAY contain any of these top-level members:
attributes: an attributes object representing some …
```

Handle resource.relationships undefined in updateOrInsertResource

---

src/utils.js
test/utils.js

Fixes #171
According to https://jsonapi.org/format/#document-links
> * a string containing the link’s URL.
> * an object (“link object”) which can contain the following members:
>   * `href`: a string containing the link’s URL.

Pagination URLs can be objects.

---

package.json
yarn.lock

`keykey` v2.x uses a very outdated version of `lru-cache`, which is incompatible with the version used by other modern and more up-to-date packages.  This PR updates the `keykey` dependency, which includes a newer version or `lru-cache`.

Upgrade keykey
